# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_urls_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='URls',
        ),
    ]
