# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-26 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200326_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableURL',
            new_name='Database',
        ),
    ]
