# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-27 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_database_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='length',
        ),
    ]
